name: Deploy to Firebase Hosting on merge (prod)
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - lszt_prod
          - lspv_prod
    environment: ${{ matrix.environment }}
    steps:
      - run: echo 'Running deplyoment for project ${{ vars.PROJECT }}'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build:prod --project=${{ vars.PROJECT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: w9jds/setup-firebase@main
        with:
          project_id: ${{ vars.FIREBASE_PROJECT }}
          tools-version: 13
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase target:apply database main ${{ vars.FIREBASE_RTDB_NAME }}
      - run: firebase deploy --only hosting,database:main
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - lszt_prod
          - lspv_prod
    environment: ${{ matrix.environment }}
    steps:
      - run: echo 'Running functions deplyoment for project ${{ vars.PROJECT }}'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: w9jds/setup-firebase@main
        with:
          project_id: ${{ vars.FIREBASE_PROJECT }}
          tools-version: 13
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: cd functions && npm ci && cd ..
      - run: firebase deploy --only functions
