name: Deploy to Firebase Hosting on merge (dev)
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - lszt-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build --project=${{ vars.PROJECT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: w9jds/setup-firebase@main
        with:
          project_id: ${{ vars.FIREBASE_PROJECT }}
          tools-version: 13
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: firebase deploy --only hosting,database
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: w9jds/setup-firebase@main
        with:
          project_id: ${{ vars.FIREBASE_PROJECT }}
          tools-version: 13
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
      - run: cd functions && npm ci && cd ..
      - run: firebase deploy --only functions
